module.exports = {
    Accept: require('./accept'),
    AddQ: require('./addq'),
    AppChannel: require('./appchannel'),
    Apply: require('./apply'),
    DelQ: require('./delq'),
    Help: require('./help'),
    Info: require('./info'),
    LogChannel: require('./logchannel'),
    Ping: require('./ping'),
    Prefix: require('./prefix'),
    Questions: require('./questions'),
    Reject: require('./reject'),
    Reviewer: require('./reviewer'),
};